name: Rust

on:
  pull_request:
    branches: [ "*" ]
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: "always"
  CARGO_INCREMENTAL: "0"
  RUSTC_WRAPPER: "sccache"
  SCCACHE_GHA_ENABLED: "true"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Install sccache
        uses: mozilla-actions/sccache-action@v0.0.3
      - name: Install `cargo-deny`
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-deny

      - name: Format
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy --workspace --all-features --all-targets -- -D warnings
      - name: Deny
        run: cargo deny check

      - name: Run tests
        run: cargo test --workspace --all-features --all-targets
      - name: Run doc tests
        run: cargo test --workspace --all-features --doc
